export interface User {
  id: string;
  email: string;
  username: string;
  avatar?: string;
  createdAt: Date;
  followers?: string[];
  following?: string[];
  bio?: string;
  isArtist?: boolean;
  isAdmin?: boolean;
}

export interface Song {
  id: string;
  title: string;
  artist: string;
  album?: string;
  genre?: string;
  duration: number;
  filePath: string;
  coverArt?: string;
  uploadedBy: string;
  createdAt: Date;
  playCount?: number;
  liked?: boolean;
  rating?: number;
  averageRating?: number;
  totalRatings?: number;
  lyrics?: string;
  mood?: string[];
  tempo?: number;
  key?: string;
  license?: string;
  source?: string;
  description?: string;
}

export interface Comment {
  id: string;
  userId: string;
  username: string;
  avatar?: string;
  songId: string;
  content: string;
  createdAt: Date;
  likes: number;
  replies?: Comment[];
}

export interface Activity {
  id: string;
  userId: string;
  username: string;
  avatar?: string;
  type: 'play' | 'like' | 'playlist_create' | 'upload' | 'follow';
  content: string;
  songId?: string;
  playlistId?: string;
  targetUserId?: string;
  createdAt: Date;
}

export interface UserStats {
  totalListeningTime: number;
  songsPlayed: number;
  favoriteGenres: { genre: string; count: number }[];
  topArtists: { artist: string; count: number }[];
  weeklyStats: { week: string; minutes: number }[];
  currentStreak: number;
}

export interface Playlist {
  id: string;
  name: string;
  description?: string;
  songs: Song[];
  userId: string;
  isPublic: boolean;
  isCollaborative?: boolean;
  collaborators?: string[];
  createdAt: Date;
  coverArt?: string;
  followers?: number;
  isWeekendSpecial?: boolean;
  lastRefreshed?: Date;
  autoGenerated?: boolean;
}

export interface PlaybackState {
  currentSong: Song | null;
  isPlaying: boolean;
  volume: number;
  currentTime: number;
  duration: number;
  queue: Song[];
  currentIndex: number;
  isShuffled: boolean;
  isRepeating: boolean;
  crossfadeEnabled: boolean;
  crossfadeDuration: number;
  equalizer: {
    bass: number;
    mid: number;
    treble: number;
    enabled: boolean;
  };
}

export interface AuthState {
  user: User | null;
  token: string | null;
  isAuthenticated: boolean;
}

export interface MoodPlaylist {
  id: string;
  name: string;
  mood: string;
  description: string;
  songs: Song[];
  color: string;
  icon: string;
}